In [93]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from word2number import w2n
import math
import warnings
warnings.filterwarnings("ignore")

In [94]:
d=pd.read_csv("hiring.csv")
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [95]:
d["experience"]=d["experience"].fillna("zero")
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [96]:
d["experience"]=d["experience"].apply(w2n.word_to_num)
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [97]:
mean_test_score=math.floor(d["test_score(out of 10)"].mean())
mean_test_score

7

In [98]:
d["test_score(out of 10)"]=d["test_score(out of 10)"].fillna(mean_test_score)
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [107]:
x=d.drop("salary($)",axis=1)
x

experience  test_score(out of 10)  interview_score(out of 10)
0           0                    8.0                           9
1           0                    8.0                           6
2           5                    6.0                           7
3           2                   10.0                          10
4           7                    9.0                           6
5           3                    7.0                          10
6          10                    7.0                           7
7          11                    7.0                           8

In [111]:
y=d["salary($)"]
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [112]:
reg=LinearRegression()
reg.fit(x,y)

LinearRegression()

In [113]:
reg.predict([[2,9,6]])

array([53713.86677124])

In [114]:
reg.predict([[12,10,10]])

array([93747.79628651])

In [115]:
reg.score(x,y)

0.9770139014273139

In [116]:
#predict 3400 sqr ft home in west windsor
reg.predict([[3400,0,0]])

array([9950707.30251829])